version: '2'
services:
  neo4j:
    image: 'bitnami/neo4j:3'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitnami'
    command: /bitnami/CSVs/dbconfig.sh
volumes:
  neo4j_data:
    driver: local
